import type { CSSProperties } from "react"
import type { CausalLearningObject, ConceptMapLearningObject, HierarchyLearningObject, PlainTextLearningObject, QuantitativeLearningObject } from "../schema/learningObject"

const box: CSSProperties = { border: "1px solid #d8d2c5", borderRadius: 10, padding: 12, background: "#fbfaf6" }

export function CausalRenderer({ object }: { object: CausalLearningObject }) {
  return <div style={{ display: "grid", gap: 8 }}>{object.edges.map(edge => <div key={`${edge.from}-${edge.to}`} style={{ display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center" }}><span style={box}>{object.nodes.find(n => n.id === edge.from)?.label}</span><span aria-label={edge.label || "causes"}>— {edge.label || "causes"} →</span><span style={box}>{object.nodes.find(n => n.id === edge.to)?.label}</span>{edge.mechanism && <small>{edge.mechanism}</small>}</div>)}{object.edges.length === 0 && object.nodes.map(node => <p key={node.id} style={box}>{node.label}</p>)}</div>
}

export function ConceptMapRenderer({ object }: { object: ConceptMapLearningObject }) {
  const width = 720, height = Math.max(220, Math.ceil(object.nodes.length / 3) * 130)
  const positions = new Map(object.nodes.map((node, index) => [node.id, { x: 120 + (index % 3) * 240, y: 55 + Math.floor(index / 3) * 120 }]))
  return <div style={{ overflowX: "auto" }}><svg role="img" aria-label={`${object.title} concept map`} viewBox={`0 0 ${width} ${height}`} style={{ minWidth: 560, width: "100%", height: "auto" }}><defs><marker id="lucent-map-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#58735d" /></marker></defs>{object.relationships.map((relationship, index) => { const from = positions.get(relationship.source), to = positions.get(relationship.target); return from && to ? <g key={`${relationship.source}-${relationship.target}-${index}`}><line x1={from.x} y1={from.y} x2={to.x} y2={to.y} stroke="#58735d" strokeWidth="2" markerEnd="url(#lucent-map-arrow)" /><text x={(from.x + to.x) / 2} y={(from.y + to.y) / 2 - 6} textAnchor="middle" fill="#58735d" fontSize="12">{relationship.relation}</text></g> : null })}{object.nodes.map(node => { const position = positions.get(node.id)!; return <g key={node.id}><rect x={position.x - 92} y={position.y - 25} width="184" height="50" rx="10" fill="#fbfaf6" stroke="#d8d2c5" /><text x={position.x} y={position.y + 5} textAnchor="middle" fill="#22221f" fontSize="13">{node.label.slice(0, 28)}</text></g> })}</svg></div>
}

function Tree({ node, depth = 0 }: { node: HierarchyLearningObject["root"]; depth?: number }) { return <li style={{ marginLeft: depth * 18, marginBottom: 8 }}><span style={box}>{node.label}</span>{node.children?.length ? <ul>{node.children.map(child => <Tree key={child.id} node={child} depth={depth + 1} />)}</ul> : null}</li> }
export function HierarchyRenderer({ object }: { object: HierarchyLearningObject }) { return <ul style={{ listStyle: "none", padding: 0, margin: 0 }}><Tree node={object.root} /></ul> }

export function QuantitativeRenderer({ object }: { object: QuantitativeLearningObject }) { return <div style={{ display: "grid", gap: 12 }}><div style={{ ...box, fontFamily: "ui-monospace, monospace", fontSize: "1.05rem" }}>{object.formula || object.relationships[0]?.expression}</div>{object.variables.length ? <dl>{object.variables.map(variable => <div key={variable.id}><dt><strong>{variable.name}</strong></dt><dd>{variable.value ?? ""}{variable.unit ? ` ${variable.unit}` : ""}{variable.explanation ? ` — ${variable.explanation}` : ""}</dd></div>)}</dl> : null}{object.givenValues?.length ? <div style={box}><strong>Given values</strong><ul>{object.givenValues.map(value => <li key={value.variable}>{value.variable} = {value.value}{value.unit ? ` ${value.unit}` : ""}</li>)}</ul></div> : null}{object.derivationSteps?.length ? <div style={box}><strong>Derivation</strong><ol>{object.derivationSteps.map(step => <li key={step}>{step}</li>)}</ol></div> : null}{object.interpretation && <p><strong>Interpretation:</strong> {object.interpretation}</p>}</div> }
export function PlainTextRenderer({ object }: { object: PlainTextLearningObject }) { return <div>{object.explanation && <p style={box}>{object.explanation}</p>}{object.paragraphs.map((paragraph, index) => <p key={`${index}-${paragraph.slice(0, 12)}`}>{paragraph}</p>)}{object.keyPoints?.length ? <><h4>Key points</h4><ul>{object.keyPoints.map(point => <li key={point}>{point}</li>)}</ul></> : null}{object.definitions?.length ? <dl>{object.definitions.map(definition => <div key={definition.term}><dt><strong>{definition.term}</strong></dt><dd>{definition.meaning}</dd></div>)}</dl> : null}</div> }
