import type { CSSProperties } from "react"
import type { CausalLearningObject, ConceptMapLearningObject, HierarchyLearningObject, PlainTextLearningObject, QuantitativeLearningObject } from "../schema/learningObject"

const box: CSSProperties = { border: "1px solid #d8d2c5", borderRadius: 12, padding: 16, background: "#fbfaf6" }
export function CausalRenderer({ object }: { object: CausalLearningObject }) { return <div style={{ display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center" }}>{object.nodes.map((n, i) => <span key={n.id} style={{ display: "inline-flex", gap: 8, alignItems: "center" }}><span style={box}>{n.label}</span>{i < object.nodes.length - 1 && <span aria-hidden="true">→</span>}</span>)}</div> }
export function ConceptMapRenderer({ object }: { object: ConceptMapLearningObject }) { return <div style={{ display: "grid", gap: 10 }}>{object.nodes.map(n => <div key={n.id} style={box}><strong>{n.label}</strong>{object.relationships.filter(r => r.from === n.id || r.to === n.id).map(r => <div key={`${r.from}-${r.to}`}><small>{r.from === n.id ? `${r.label} → ${object.nodes.find(x => x.id === r.to)?.label}` : `← ${r.label} ${object.nodes.find(x => x.id === r.from)?.label}`}</small></div>)}</div>)}</div> }
function Tree({ node, depth = 0 }: { node: HierarchyLearningObject["root"]; depth?: number }) { return <li style={{ marginLeft: depth * 14 }}><span style={box}>{node.label}</span>{node.children?.length ? <ul>{node.children.map(child => <Tree key={child.id} node={child} depth={depth + 1} />)}</ul> : null}</li> }
export function HierarchyRenderer({ object }: { object: HierarchyLearningObject }) { return <ul><Tree node={object.root} /></ul> }
export function QuantitativeRenderer({ object }: { object: QuantitativeLearningObject }) { return <div style={{ display: "grid", gap: 12 }}>{object.relationships.map(r => <div key={r.expression} style={{ ...box, fontFamily: "ui-monospace, monospace", fontSize: "1.05rem" }}>{r.expression}</div>)}{object.variables.length ? <dl>{object.variables.map(v => <div key={v.id}><dt><strong>{v.name}</strong></dt><dd>{v.value ?? ""}{v.unit ? ` ${v.unit}` : ""}{v.explanation ? ` — ${v.explanation}` : ""}</dd></div>)}</dl> : null}</div> }
export function PlainTextRenderer({ object }: { object: PlainTextLearningObject }) { return <div>{object.paragraphs.map((p, i) => <p key={`${i}-${p.slice(0, 12)}`}>{p}</p>)}{object.keyPoints?.length ? <ul>{object.keyPoints.map(p => <li key={p}>{p}</li>)}</ul> : null}{object.definitions?.length ? <dl>{object.definitions.map(d => <div key={d.term}><dt><strong>{d.term}</strong></dt><dd>{d.meaning}</dd></div>)}</dl> : null}</div> }
