import type { StepThroughMechanismData } from "./StepThroughMechanism"

export const gramSchmidtGolden: StepThroughMechanismData = {
  sceneType: "vector_scene",
  learningGoal: "Understand geometrically why subtracting projections produces orthogonal directions.",
  entities: [
    { id: "v1", label: "u₁ = v₁", color: "#1d9e75" },
    { id: "v2", label: "v₂", color: "#bf6b3a" },
    { id: "projection", label: "projᵤ₁(v₂)", color: "#9a7b27" },
    { id: "u2", label: "u₂ (orthogonal remainder)", color: "#26215c" },
  ],
  stages: [
    { title: "Start with overlapping directions", explanation: "v₁ and v₂ share some direction. We keep v₁ as the first basis direction and compare v₂ against it.", activeEntityIds: ["v1", "v2"], vectors: [{ id: "v1", x: 220, y: 0, color: "#1d9e75", label: "u₁ = v₁" }, { id: "v2", x: 185, y: 105, color: "#bf6b3a", label: "v₂" }], visual: { type: "vector_scene", activeEntityIds: ["v1", "v2"], operations: [{ type: "highlight", entityIds: ["v1", "v2"], reason: "Compare the new vector with the direction already kept." }] } },
    { title: "Expose the shared component", explanation: "The projection is the part of v₂ already pointing along u₁. It is the overlap we need to remove.", equation: "projᵤ₁(v₂)", activeEntityIds: ["v2", "projection"], vectors: [{ id: "v2", x: 185, y: 105, color: "#bf6b3a", label: "v₂" }, { id: "projection", x: 185, y: 0, color: "#9a7b27", dashed: true, label: "projection" }], visual: { type: "vector_scene", activeEntityIds: ["v2", "projection"], operations: [{ type: "project", entityIds: ["v2", "v1", "projection"], reason: "Identify the component already along u₁." }], relationships: [{ source: "projection", target: "v1", relation: "parallel_to" }] } },
    { title: "Subtract the overlap", explanation: "Subtracting projᵤ₁(v₂) removes the part of v₂ parallel to u₁, leaving only the new direction.", equation: "u₂ = v₂ − projᵤ₁(v₂)", activeEntityIds: ["v2", "projection", "u2"], vectors: [{ id: "v2", x: 185, y: 105, color: "#bf6b3a", dashed: true, label: "v₂ (before)" }, { id: "projection", x: 185, y: 0, color: "#9a7b27", dashed: true, label: "projection" }, { id: "u2", x: 0, y: 105, color: "#26215c", label: "u₂" }], visual: { type: "vector_scene", activeEntityIds: ["v2", "projection", "u2"], operations: [{ type: "subtract", entityIds: ["v2", "projection", "u2"], reason: "Remove the component already pointing along u₁.", result: "u₂ is the remaining direction." }] } },
    { title: "The remainder is perpendicular", explanation: "The remaining component has no u₁ direction left, so u₂ is orthogonal to u₁. For later vectors, remove projections onto every earlier orthogonal direction.", equation: "uₖ = vₖ − Σ projᵤⱼ(vₖ)", activeEntityIds: ["v1", "u2"], vectors: [{ id: "v1", x: 220, y: 0, color: "#1d9e75", label: "u₁" }, { id: "u2", x: 0, y: 125, color: "#26215c", label: "u₂" }], visual: { type: "vector_scene", activeEntityIds: ["v1", "u2"], operations: [{ type: "reveal", entityIds: ["u2"], result: "The remainder becomes the next basis direction." }], relationships: [{ source: "u2", target: "v1", relation: "perpendicular_to", explanation: "u₂ has no component left along u₁." }] } },
  ],
  prediction: { prompt: "For v₃, which previous directions must be removed?", options: ["u₁", "u₂", "Both u₁ and u₂"], answer: 2, reveal: "Each previous orthogonal direction can contribute an overlap, so Gram–Schmidt subtracts both projections before continuing." },
  conclusion: "Gram–Schmidt builds new orthogonal directions by removing the components already explained by earlier basis vectors; normalization only changes their length.",
}

/* Photosynthesis proof-of-concept is assembled from reusable mechanism primitives. */
const photoBase = [{ id: "lumen", kind: "region" as const, label: "Lumen (inside)", x: 60, y: 55, width: 600, height: 105, color: "#e4edf2" }, { id: "membrane", kind: "boundary" as const, x: 60, y: 180, x2: 660, y2: 180 }, { id: "stroma", kind: "region" as const, label: "Stroma (outside)", x: 60, y: 205, width: 600, height: 105, color: "#f0eadf" }]
const photoScene = (extra: any[]) => ({ type: "mechanism_scene" as const, primitives: [...photoBase, ...extra] })
export const photosynthesisGolden: StepThroughMechanismData = {
  sceneType: "mechanism_scene",
  learningGoal: "Follow how light energy becomes ATP and NADPH across the thylakoid membrane.",
  entities: [],
  stages: [
    { title: "Set up the membrane", explanation: "The membrane separates lumen from stroma, allowing a proton gradient to store energy.", activeEntityIds: [], visual: photoScene([{ id: "ps", kind: "object", label: "Photosystem", x: 180, y: 145, width: 90, height: 45, color: "#88a66d" }]) },
    { title: "Photon excites chlorophyll", explanation: "A photon arrives and raises a chlorophyll electron to a higher-energy state.", activeEntityIds: [], visual: photoScene([{ id: "ps", kind: "object", label: "Photosystem", x: 180, y: 145, width: 90, height: 45, color: "#88a66d" }, { id: "photon", kind: "particle", label: "photon", x: 90, y: 120, color: "#d69b3c" }, { id: "photon-flow", kind: "flow", label: "light", x: 105, y: 120, x2: 175, y2: 160 }]) },
    { title: "Electrons enter transport", explanation: "The energized electron moves through the electron-transport chain, releasing energy step by step.", activeEntityIds: [], visual: photoScene([{ id: "ps", kind: "object", label: "Photosystem", x: 130, y: 145, width: 90, height: 45, color: "#88a66d" }, { id: "chain", kind: "object", label: "ETC", x: 390, y: 145, width: 90, height: 45, color: "#7891a3" }, { id: "electron", kind: "particle", label: "e−", x: 230, y: 160, color: "#4d8764" }, { id: "electron-flow", kind: "flow", label: "energized e−", x: 220, y: 160, x2: 385, y2: 160 }]) },
    { title: "Build the proton gradient", explanation: "Transport-chain energy pumps H⁺ into the lumen, storing energy as a concentration gradient.", activeEntityIds: [], visual: photoScene([{ id: "chain", kind: "object", label: "ETC pumps H⁺", x: 300, y: 145, width: 120, height: 45, color: "#7891a3" }, { id: "h1", kind: "particle", label: "H⁺", x: 190, y: 105, color: "#c45c54" }, { id: "h2", kind: "particle", label: "H⁺", x: 250, y: 125, color: "#c45c54" }, { id: "h3", kind: "particle", label: "H⁺", x: 490, y: 90, color: "#c45c54" }, { id: "pump", kind: "flow", label: "pump", x: 420, y: 160, x2: 480, y2: 110 }]) },
    { title: "Protons power ATP synthase", explanation: "H⁺ flows back through ATP synthase; stored gradient energy drives ATP formation.", activeEntityIds: [], visual: photoScene([{ id: "atp", kind: "object", label: "ATP synthase", x: 300, y: 150, width: 120, height: 55, color: "#88a66d" }, { id: "proton-flow", kind: "flow", label: "H⁺ flow", x: 360, y: 120, x2: 360, y2: 220 }, { id: "ATP", kind: "particle", label: "ATP", x: 475, y: 250, color: "#4d8764" }]) },
    { title: "Reduce NADP⁺", explanation: "A terminal electron and H⁺ reduce NADP⁺ to NADPH for later carbon fixation.", activeEntityIds: [], visual: photoScene([{ id: "ps2", kind: "object", label: "Photosystem I", x: 120, y: 145, width: 120, height: 45, color: "#88a66d" }, { id: "nadp", kind: "object", label: "NADP⁺ → NADPH", x: 460, y: 145, width: 150, height: 45, color: "#7891a3" }, { id: "nadp-flow", kind: "flow", label: "e− + H⁺", x: 245, y: 165, x2: 450, y2: 165 }, { id: "NADPH", kind: "particle", label: "NADPH", x: 525, y: 235, color: "#4d8764" }]) },
    { title: "The light reactions complete", explanation: "Light drives electron flow, water splitting releases O₂, the gradient powers ATP, and NADPH carries reducing power onward.", activeEntityIds: [], visual: photoScene([{ id: "water", kind: "object", label: "H₂O → O₂", x: 70, y: 110, width: 100, height: 42, color: "#7891a3" }, { id: "ps", kind: "object", label: "PSII", x: 190, y: 145, width: 75, height: 42, color: "#88a66d" }, { id: "chain", kind: "object", label: "ETC + H⁺", x: 300, y: 145, width: 100, height: 42, color: "#7891a3" }, { id: "atp", kind: "object", label: "ATP synthase → ATP", x: 430, y: 145, width: 145, height: 42, color: "#88a66d" }, { id: "nadph", kind: "object", label: "NADPH", x: 590, y: 145, width: 75, height: 42, color: "#4d8764" }, { id: "electron-flow", kind: "flow", label: "e−", x: 265, y: 165, x2: 425, y2: 165 }]) },
  ],
  prediction: { prompt: "What would happen if the proton gradient disappeared?", options: ["ATP production would stop", "NADPH would turn into glucose immediately"], answer: 0, reveal: "Without the gradient, H⁺ has no stored energy to drive ATP synthase, so ATP production falls." },
  conclusion: "The light-dependent reactions convert photon energy into ATP and NADPH while splitting water and releasing oxygen.",
}
